/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WidgetSlugRouteImport } from './routes/widget/$slug'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as PSlugIndexRouteImport } from './routes/p/$slug/index'
import { Route as PSlugRoadmapRouteImport } from './routes/p/$slug/roadmap'
import { Route as PSlugFeedbackRouteImport } from './routes/p/$slug/feedback'
import { Route as AuthedProjectsNewRouteImport } from './routes/_authed/projects/new'
import { Route as AuthedProjectsProjectIdRouteRouteImport } from './routes/_authed/projects/$projectId/route'
import { Route as AuthedProjectsProjectIdSettingsRouteImport } from './routes/_authed/projects/$projectId/settings'
import { Route as AuthedProjectsProjectIdRoadmapRouteImport } from './routes/_authed/projects/$projectId/roadmap'
import { Route as AuthedProjectsProjectIdFeedbackRouteImport } from './routes/_authed/projects/$projectId/feedback'
import { Route as AuthedProjectsProjectIdChangelogIndexRouteImport } from './routes/_authed/projects/$projectId/changelog/index'
import { Route as AuthedProjectsProjectIdChangelogNewRouteImport } from './routes/_authed/projects/$projectId/changelog/new'
import { Route as AuthedProjectsProjectIdChangelogChangelogIdEditRouteImport } from './routes/_authed/projects/$projectId/changelog/$changelogId/edit'

const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetSlugRoute = WidgetSlugRouteImport.update({
  id: '/widget/$slug',
  path: '/widget/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const PSlugIndexRoute = PSlugIndexRouteImport.update({
  id: '/p/$slug/',
  path: '/p/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoadmapRoute = PSlugRoadmapRouteImport.update({
  id: '/p/$slug/roadmap',
  path: '/p/$slug/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugFeedbackRoute = PSlugFeedbackRouteImport.update({
  id: '/p/$slug/feedback',
  path: '/p/$slug/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProjectsNewRoute = AuthedProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsProjectIdRouteRoute =
  AuthedProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProjectsProjectIdSettingsRoute =
  AuthedProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedProjectsProjectIdRouteRoute,
  } as any)
const AuthedProjectsProjectIdRoadmapRoute =
  AuthedProjectsProjectIdRoadmapRouteImport.update({
    id: '/roadmap',
    path: '/roadmap',
    getParentRoute: () => AuthedProjectsProjectIdRouteRoute,
  } as any)
const AuthedProjectsProjectIdFeedbackRoute =
  AuthedProjectsProjectIdFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthedProjectsProjectIdRouteRoute,
  } as any)
const AuthedProjectsProjectIdChangelogIndexRoute =
  AuthedProjectsProjectIdChangelogIndexRouteImport.update({
    id: '/changelog/',
    path: '/changelog/',
    getParentRoute: () => AuthedProjectsProjectIdRouteRoute,
  } as any)
const AuthedProjectsProjectIdChangelogNewRoute =
  AuthedProjectsProjectIdChangelogNewRouteImport.update({
    id: '/changelog/new',
    path: '/changelog/new',
    getParentRoute: () => AuthedProjectsProjectIdRouteRoute,
  } as any)
const AuthedProjectsProjectIdChangelogChangelogIdEditRoute =
  AuthedProjectsProjectIdChangelogChangelogIdEditRouteImport.update({
    id: '/changelog/$changelogId/edit',
    path: '/changelog/$changelogId/edit',
    getParentRoute: () => AuthedProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/widget/$slug': typeof WidgetSlugRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdRouteRouteWithChildren
  '/projects/new': typeof AuthedProjectsNewRoute
  '/p/$slug/feedback': typeof PSlugFeedbackRoute
  '/p/$slug/roadmap': typeof PSlugRoadmapRoute
  '/p/$slug/': typeof PSlugIndexRoute
  '/projects/$projectId/feedback': typeof AuthedProjectsProjectIdFeedbackRoute
  '/projects/$projectId/roadmap': typeof AuthedProjectsProjectIdRoadmapRoute
  '/projects/$projectId/settings': typeof AuthedProjectsProjectIdSettingsRoute
  '/projects/$projectId/changelog/new': typeof AuthedProjectsProjectIdChangelogNewRoute
  '/projects/$projectId/changelog/': typeof AuthedProjectsProjectIdChangelogIndexRoute
  '/projects/$projectId/changelog/$changelogId/edit': typeof AuthedProjectsProjectIdChangelogChangelogIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/widget/$slug': typeof WidgetSlugRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdRouteRouteWithChildren
  '/projects/new': typeof AuthedProjectsNewRoute
  '/p/$slug/feedback': typeof PSlugFeedbackRoute
  '/p/$slug/roadmap': typeof PSlugRoadmapRoute
  '/p/$slug': typeof PSlugIndexRoute
  '/projects/$projectId/feedback': typeof AuthedProjectsProjectIdFeedbackRoute
  '/projects/$projectId/roadmap': typeof AuthedProjectsProjectIdRoadmapRoute
  '/projects/$projectId/settings': typeof AuthedProjectsProjectIdSettingsRoute
  '/projects/$projectId/changelog/new': typeof AuthedProjectsProjectIdChangelogNewRoute
  '/projects/$projectId/changelog': typeof AuthedProjectsProjectIdChangelogIndexRoute
  '/projects/$projectId/changelog/$changelogId/edit': typeof AuthedProjectsProjectIdChangelogChangelogIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/explore': typeof ExploreRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/widget/$slug': typeof WidgetSlugRoute
  '/_authed/projects/$projectId': typeof AuthedProjectsProjectIdRouteRouteWithChildren
  '/_authed/projects/new': typeof AuthedProjectsNewRoute
  '/p/$slug/feedback': typeof PSlugFeedbackRoute
  '/p/$slug/roadmap': typeof PSlugRoadmapRoute
  '/p/$slug/': typeof PSlugIndexRoute
  '/_authed/projects/$projectId/feedback': typeof AuthedProjectsProjectIdFeedbackRoute
  '/_authed/projects/$projectId/roadmap': typeof AuthedProjectsProjectIdRoadmapRoute
  '/_authed/projects/$projectId/settings': typeof AuthedProjectsProjectIdSettingsRoute
  '/_authed/projects/$projectId/changelog/new': typeof AuthedProjectsProjectIdChangelogNewRoute
  '/_authed/projects/$projectId/changelog/': typeof AuthedProjectsProjectIdChangelogIndexRoute
  '/_authed/projects/$projectId/changelog/$changelogId/edit': typeof AuthedProjectsProjectIdChangelogChangelogIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/dashboard'
    | '/widget/$slug'
    | '/projects/$projectId'
    | '/projects/new'
    | '/p/$slug/feedback'
    | '/p/$slug/roadmap'
    | '/p/$slug/'
    | '/projects/$projectId/feedback'
    | '/projects/$projectId/roadmap'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/changelog/new'
    | '/projects/$projectId/changelog/'
    | '/projects/$projectId/changelog/$changelogId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/dashboard'
    | '/widget/$slug'
    | '/projects/$projectId'
    | '/projects/new'
    | '/p/$slug/feedback'
    | '/p/$slug/roadmap'
    | '/p/$slug'
    | '/projects/$projectId/feedback'
    | '/projects/$projectId/roadmap'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/changelog/new'
    | '/projects/$projectId/changelog'
    | '/projects/$projectId/changelog/$changelogId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/explore'
    | '/_authed/dashboard'
    | '/widget/$slug'
    | '/_authed/projects/$projectId'
    | '/_authed/projects/new'
    | '/p/$slug/feedback'
    | '/p/$slug/roadmap'
    | '/p/$slug/'
    | '/_authed/projects/$projectId/feedback'
    | '/_authed/projects/$projectId/roadmap'
    | '/_authed/projects/$projectId/settings'
    | '/_authed/projects/$projectId/changelog/new'
    | '/_authed/projects/$projectId/changelog/'
    | '/_authed/projects/$projectId/changelog/$changelogId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  WidgetSlugRoute: typeof WidgetSlugRoute
  PSlugFeedbackRoute: typeof PSlugFeedbackRoute
  PSlugRoadmapRoute: typeof PSlugRoadmapRoute
  PSlugIndexRoute: typeof PSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/$slug': {
      id: '/widget/$slug'
      path: '/widget/$slug'
      fullPath: '/widget/$slug'
      preLoaderRoute: typeof WidgetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/p/$slug/': {
      id: '/p/$slug/'
      path: '/p/$slug'
      fullPath: '/p/$slug/'
      preLoaderRoute: typeof PSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug/roadmap': {
      id: '/p/$slug/roadmap'
      path: '/p/$slug/roadmap'
      fullPath: '/p/$slug/roadmap'
      preLoaderRoute: typeof PSlugRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug/feedback': {
      id: '/p/$slug/feedback'
      path: '/p/$slug/feedback'
      fullPath: '/p/$slug/feedback'
      preLoaderRoute: typeof PSlugFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/projects/new': {
      id: '/_authed/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthedProjectsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId': {
      id: '/_authed/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthedProjectsProjectIdRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId/settings': {
      id: '/_authed/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AuthedProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRouteRoute
    }
    '/_authed/projects/$projectId/roadmap': {
      id: '/_authed/projects/$projectId/roadmap'
      path: '/roadmap'
      fullPath: '/projects/$projectId/roadmap'
      preLoaderRoute: typeof AuthedProjectsProjectIdRoadmapRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRouteRoute
    }
    '/_authed/projects/$projectId/feedback': {
      id: '/_authed/projects/$projectId/feedback'
      path: '/feedback'
      fullPath: '/projects/$projectId/feedback'
      preLoaderRoute: typeof AuthedProjectsProjectIdFeedbackRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRouteRoute
    }
    '/_authed/projects/$projectId/changelog/': {
      id: '/_authed/projects/$projectId/changelog/'
      path: '/changelog'
      fullPath: '/projects/$projectId/changelog/'
      preLoaderRoute: typeof AuthedProjectsProjectIdChangelogIndexRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRouteRoute
    }
    '/_authed/projects/$projectId/changelog/new': {
      id: '/_authed/projects/$projectId/changelog/new'
      path: '/changelog/new'
      fullPath: '/projects/$projectId/changelog/new'
      preLoaderRoute: typeof AuthedProjectsProjectIdChangelogNewRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRouteRoute
    }
    '/_authed/projects/$projectId/changelog/$changelogId/edit': {
      id: '/_authed/projects/$projectId/changelog/$changelogId/edit'
      path: '/changelog/$changelogId/edit'
      fullPath: '/projects/$projectId/changelog/$changelogId/edit'
      preLoaderRoute: typeof AuthedProjectsProjectIdChangelogChangelogIdEditRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRouteRoute
    }
  }
}

interface AuthedProjectsProjectIdRouteRouteChildren {
  AuthedProjectsProjectIdFeedbackRoute: typeof AuthedProjectsProjectIdFeedbackRoute
  AuthedProjectsProjectIdRoadmapRoute: typeof AuthedProjectsProjectIdRoadmapRoute
  AuthedProjectsProjectIdSettingsRoute: typeof AuthedProjectsProjectIdSettingsRoute
  AuthedProjectsProjectIdChangelogNewRoute: typeof AuthedProjectsProjectIdChangelogNewRoute
  AuthedProjectsProjectIdChangelogIndexRoute: typeof AuthedProjectsProjectIdChangelogIndexRoute
  AuthedProjectsProjectIdChangelogChangelogIdEditRoute: typeof AuthedProjectsProjectIdChangelogChangelogIdEditRoute
}

const AuthedProjectsProjectIdRouteRouteChildren: AuthedProjectsProjectIdRouteRouteChildren =
  {
    AuthedProjectsProjectIdFeedbackRoute: AuthedProjectsProjectIdFeedbackRoute,
    AuthedProjectsProjectIdRoadmapRoute: AuthedProjectsProjectIdRoadmapRoute,
    AuthedProjectsProjectIdSettingsRoute: AuthedProjectsProjectIdSettingsRoute,
    AuthedProjectsProjectIdChangelogNewRoute:
      AuthedProjectsProjectIdChangelogNewRoute,
    AuthedProjectsProjectIdChangelogIndexRoute:
      AuthedProjectsProjectIdChangelogIndexRoute,
    AuthedProjectsProjectIdChangelogChangelogIdEditRoute:
      AuthedProjectsProjectIdChangelogChangelogIdEditRoute,
  }

const AuthedProjectsProjectIdRouteRouteWithChildren =
  AuthedProjectsProjectIdRouteRoute._addFileChildren(
    AuthedProjectsProjectIdRouteRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedProjectsProjectIdRouteRoute: typeof AuthedProjectsProjectIdRouteRouteWithChildren
  AuthedProjectsNewRoute: typeof AuthedProjectsNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedProjectsProjectIdRouteRoute:
    AuthedProjectsProjectIdRouteRouteWithChildren,
  AuthedProjectsNewRoute: AuthedProjectsNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ExploreRoute: ExploreRoute,
  WidgetSlugRoute: WidgetSlugRoute,
  PSlugFeedbackRoute: PSlugFeedbackRoute,
  PSlugRoadmapRoute: PSlugRoadmapRoute,
  PSlugIndexRoute: PSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
